<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
	  <PackageReference Include="Zack.AnyDBConfigProvider" Version="1.1.4" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
	  <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
	  <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />

  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Ron.ASPNETCore\Ron.ASPNETCore.csproj" />
		<ProjectReference Include="..\Ron.Commons\Ron.Commons.csproj" />
		<ProjectReference Include="..\Ron.EventBus\Ron.EventBus.csproj" />
		<ProjectReference Include="..\Ron.Infrastructure\Ron.Infrastructure.csproj" />
		<ProjectReference Include="..\Ron.JWT\Ron.JWT.csproj" />
	</ItemGroup>
</Project>
