<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <Authors>Zack Yang</Authors>
    <Company>Zack Yang</Company>
    <Version>1.1.3</Version>
    <PackageProjectUrl>https://github.com/yangzhongke/NETBookMaterials</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yangzhongke/NETBookMaterials</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
    <PackageReference Include="RedLock.net" Version="2.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ron.Commons\Ron.Commons.csproj" />
    <ProjectReference Include="..\Ron.DomainCommons\Ron.DomainCommons.csproj" />
  </ItemGroup>
</Project>
